In [1]:
import numpy as np

# A partir de listas de python

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
arr_lista = np.array(lista)

arr_lista

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
arr_matriz = np.array(matriz)

arr_matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Desde Numpy

## Valores consecutivos

In [4]:
# Crea arrays con valores consecutivos dentro de un intervalo dado:

print(np.arange(0,10))
# - El tercer parámetro indica los pasos (steps) en los que se toman los datos
print(np.arange(0,20,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [5]:
# Crea un array con las siguientes condiciones:
# np.linspaces(valor_inicial,valor_final,cantidad_de_elementos)

# El paso entre los elementos es el mismo
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

## Llenar con números aleatorios

In [6]:
# Sin parametro, crea un número aleatorio entre el 0 y el 1
np.random.rand()

0.06296092216873694

In [7]:
np.random.rand(4) # rand(cantidad_elementos)

array([0.19711502, 0.10755353, 0.30762546, 0.85256979])

In [8]:
np.random.rand(4,2,3) # rand(cantidad_elementos)

# La cantidad de atributos es la cantidad de dimansiones del array
# El valor de cada atributo es la cantidad de elementos de la dimensión

array([[[0.14330989, 0.63482413, 0.83681073],
        [0.89470229, 0.74828387, 0.54572453]],

       [[0.26436218, 0.4025332 , 0.39702086],
        [0.01369533, 0.26530578, 0.22664492]],

       [[0.26003194, 0.62126272, 0.0165067 ],
        [0.8750442 , 0.5950117 , 0.71076007]],

       [[0.73598748, 0.27909406, 0.69728445],
        [0.49401188, 0.91353968, 0.65359479]]])

In [9]:
# Arroja un número entero aleatorio dentro de un intervalo definido:
# Ejemplo: número aleatorio entre 1 y 15
np.random.randint(1,15)

8

In [10]:
# Crea un array del tamaño y dimensiones deseadas con números enteros aleatorios dentro de un intervalo definido:
# Ejemplo: matriz de 10 por 10 con números enteros aleatorios entre 1 y 100
np.random.randint(1,100,(10,10))

array([[66, 40, 69, 64, 19, 12, 63, 48, 97, 65],
       [44, 29, 37, 58, 82, 33, 83, 63, 48, 18],
       [83, 54, 47, 89, 27, 81, 35, 52, 90, 35],
       [ 2, 90, 70, 21, 56, 78,  7, 91, 86, 42],
       [93,  8, 55, 91, 92, 97, 62, 46, 80, 54],
       [47, 33, 16, 88, 57, 98, 25, 67,  6, 44],
       [63, 84, 19, 42, 38, 11, 72, 56, 73, 75],
       [80, 93, 14, 17, 92, 26, 27, 47, 49, 59],
       [91, 81, 30, 58, 15, 41, 24, 81, 77, 20],
       [47, 90, 10, 55,  5, 64, 10, 86, 53,  2]], dtype=int32)

## Arrays especiales

In [11]:
# Crea arrays de ceros (np.zeros()) con las dimensiones establecidas
# - Ayuda a crear esquemas

# Vector:
print(f'{np.zeros(3)}\n')
# Matriz:
print(np.zeros((5,5)))


[0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
# Crea arrays de unos (np.ones()) con las dimensiones establecidas
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Crea una matriz unitaria del tamaño establecido

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Creando un trozo de array a apartir de otro array (forma tradicional)

In [14]:
arr = np.arange(0,11)
print(f'Original: {arr}')
trozo_de_arr = arr[0:6]
print(f'Trozo extraido: {trozo_de_arr}\n')

# Aquí se sobreescribe trozo_de_arr
trozo_de_arr[:] = 0
print(f'Trozo modificado: {trozo_de_arr}')

# El problema es que como hace referencia a arr, también lo sobreescribe y daña el array original
print(f'Original sobreescrito: {arr}')

Original: [ 0  1  2  3  4  5  6  7  8  9 10]
Trozo extraido: [0 1 2 3 4 5]

Trozo modificado: [0 0 0 0 0 0]
Original sobreescrito: [ 0  0  0  0  0  0  6  7  8  9 10]


# Usando .copy()

In [15]:
# De esta forma arr_copy ocupa un espacio diferente de memoria y se elimina el riesgo de sobreescribir el array original

# IMPORTANTE: Siempre que quiera sacar trozos de un array, usar copy, para no correr el riesgo de modificar el original

arr = np.arange(0,11)
arr_copy = arr.copy()
print(f'Original: {arr}')
print(f'Copia: {arr_copy}\n')

# Modificando la copia del array original
arr_copy[:] = 100
print(f'Copia modificada: {arr_copy}')

# El array original no se modifica
print(f'Original no alterado: {arr}')

Original: [ 0  1  2  3  4  5  6  7  8  9 10]
Copia: [ 0  1  2  3  4  5  6  7  8  9 10]

Copia modificada: [100 100 100 100 100 100 100 100 100 100 100]
Original no alterado: [ 0  1  2  3  4  5  6  7  8  9 10]
