In [5]:
import numpy as np

In [6]:
lista = [1,2,3,4,5,6,7,8,9]
arr_lista = np.array(lista)

arr_lista

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
arr_matriz = np.array(matriz)

arr_matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Acceder a valores específicos de un array

In [8]:
arr_lista[0]

np.int64(1)

In [9]:
# En el caso de una matriz, se puede hacer de las siguientes dos formas:

# Forma 1:
arr_matriz[0][2]

np.int64(3)

In [10]:
# Forma 2:
arr_matriz[0,2]

np.int64(3)

# Slicing para recorrer arrays

In [11]:
# recorre desde el elemento con índice 3 hasta el 6
print(arr_lista)
arr_lista[3:6]

[1 2 3 4 5 6 7 8 9]


array([4, 5, 6])

In [12]:
# Recorre el primer elemento de cada lista dentro de la matriz
print(arr_matriz)
arr_matriz[:,0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 4, 7])

In [13]:
# Empieza a recorrer el array desde el índice 2 (cuenta el elemento del índice 2)
print(arr_lista)
arr_lista[2:]

[1 2 3 4 5 6 7 8 9]


array([3, 4, 5, 6, 7, 8, 9])

In [14]:
# Recorrer el array hasta el índice 5 (sin contar el elemento del índice 5)
print(arr_lista)
arr_lista[:5]

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5])

# Mostrar objetos de 3 en 3

In [15]:
print(arr_lista)
arr_lista[::3]


[1 2 3 4 5 6 7 8 9]


array([1, 4, 7])