In [24]:
import numpy as np

# Creando arrays de diferentes dimensiones

In [25]:
scalar = np.array(42)
print(f'Número de dimensiones: {scalar.ndim}')
scalar

Número de dimensiones: 0


array(42)

In [26]:
vector = np.array([1,2,3,4])
print(f'Número de dimensiones {vector.ndim}')
vector

Número de dimensiones 1


array([1, 2, 3, 4])

In [27]:
matriz = np.array([[1,2,3],[4,5,6]])
print(f'Número de dimensiones {matriz.ndim}')
matriz

Número de dimensiones 2


array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
tensor_3d = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[32,45,65]]])
print(f'Número de dimensiones {tensor_3d.ndim}')
tensor_3d

Número de dimensiones 3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [32, 45, 65]]])

# Agregar o eliminar dimensiones

In [29]:
# Expandiendo un array una dimensión:

# 0 -> filas
# 1 -> columnas

# De esta forma se indica como se va a expandir el array. Solo son validos esos parámetros

expand = np.expand_dims(np.array([1,2,3,4]),axis=1)
print(expand)
expand.ndim

[[1]
 [2]
 [3]
 [4]]


2

In [30]:
# ndim indica la cantidad mínima de dimensiones que tiene el array al ser creado

vector = np.array([1,2,3,4],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [31]:
# Comprime al número "correcto" de dimensiones (elimina las que no se estén ocupando)
# NOTA: primero se debe ejecutar la casilla de código anterior para que se pueda ver el efecto de la función squeeze()

print(f'Dimensiones: {vector.ndim} -->',vector)
vector_2 = np.squeeze(vector)
print(f'Dimensiones: {vector_2.ndim} --->',vector_2)

Dimensiones: 10 --> [[[[[[[[[[1 2 3 4]]]]]]]]]]
Dimensiones: 1 ---> [1 2 3 4]


# Shape y reshape

In [32]:
arr = np.random.randint(0,10,(3,2,2))
arr

array([[[9, 6],
        [6, 5]],

       [[6, 0],
        [0, 2]],

       [[3, 2],
        [6, 0]]], dtype=int32)

In [33]:
arr.shape

(3, 2, 2)

_reshape_ cambia la forma del array

NOTA: Se tiene que cambiar a una forma que soporte el array original (misma cantidad de datos)

In [34]:
# Forma 1:
arr.reshape(2,6)

array([[9, 6, 6, 5, 6, 0],
       [0, 2, 3, 2, 6, 0]], dtype=int32)

In [35]:
# Forma 2:
np.reshape(arr,(2,6))

array([[9, 6, 6, 5, 6, 0],
       [0, 2, 3, 2, 6, 0]], dtype=int32)

Cambiar la forma de manera específica

In [36]:
# Reacomoda el array como en el lenguaje C:
np.reshape(arr,(2,6),'C')

array([[9, 6, 6, 5, 6, 0],
       [0, 2, 3, 2, 6, 0]], dtype=int32)

In [37]:
# Reacomoda el array como en el lenguaje Fortran:
np.reshape(arr,(2,6),'F')

array([[9, 3, 0, 6, 2, 2],
       [6, 6, 6, 0, 5, 0]], dtype=int32)

In [38]:
# Reacomoda el arreglo de la forma más optima para el almacenamiento de la computadora: 
# - Tipo C
# - Tipo F
np.reshape(arr,(2,6),'A')

array([[9, 6, 6, 5, 6, 0],
       [0, 2, 3, 2, 6, 0]], dtype=int32)