In [1]:
import numpy as np

# Tipo de dato por defecto

In [19]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

# Cambiar el tipo de dato de int64 a float64

In [14]:
# Forma 1:
# Se puede usar para crear un array con el tipo de dato deseado
arr_1 = np.array([1,2,3],dtype='float64')

print(f'Tipo de dato: {arr_1.dtype}')
arr_1

Tipo de dato: float64


array([1., 2., 3.])

In [15]:
# Forma 2:
# Se puede usar para cambiar el tipo de dato de un array previamente creado
arr_2 = np.array([1,2,3])
arr_2 = arr_2.astype(np.float64)

print(f'Tipo de dato: {arr_2.dtype}')
arr_2

Tipo de dato: float64


array([1., 2., 3.])

# Cambiar a otros tipos de datos

In [18]:
# Cambio de entero a booleano:
arr = np.array([0,1,2,3])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True])

In [10]:
# Cambio de entero a cadena de texto:
arr = np.array([1,2,3])
arr = arr.astype(np.string_)
arr

array([b'1', b'2', b'3'], dtype='|S21')

In [11]:
# Cambio de un tipo de entero (int64) a otro tipo de entero (int8):
arr = np.array(['1','2','3'])
arr = arr.astype(np.int8)
arr

array([1, 2, 3], dtype=int8)