In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

# Formas de aplicar condiciones

In [3]:
# Forma 1:
# Crea una variable con las condiciones y luego usa como parámetro esa variable.

# La condición creará un array booleano dando True a los valores que la cumplan y False a los que no
indices_cond = arr > 5
# Se ocupa la lista booleana como parámetro del array original
lista_condicion_aplicada = arr[indices_cond]

print(f'Lista original: {arr}\n')
print(f'Lista booleana de condiciones: {indices_cond}\n')
print(f'Lista con la condición aplicada: {lista_condicion_aplicada}')

Lista original: [ 1  2  3  4  5  6  7  8  9 10]

Lista booleana de condiciones: [False False False False False  True  True  True  True  True]

Lista con la condición aplicada: [ 6  7  8  9 10]


In [4]:
# Forma 2:
# aplicar la condición directamente como parámetro del array

lista_condicion_aplicada = arr[arr>5]

print(f'Lista original: {arr}\n')
print(f'Lista con la condición aplicada: {lista_condicion_aplicada}')


Lista original: [ 1  2  3  4  5  6  7  8  9 10]

Lista con la condición aplicada: [ 6  7  8  9 10]


# Usando las condiciones

In [5]:
# Aplica dos condiciones al array

arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [6]:
# Cambia el valor de los datos que cumplen con la condición establecida

arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)