In [14]:
import numpy as np

# Operaciones con listas de python

In [15]:
lista = [1,2]
lista

[1, 2]

In [16]:
# La lista de python no multiplica cada término por 2, duplica la lista
lista * 2

[1, 2, 1, 2]

# Operaciones con arrays

In [17]:
arr = np.arange(0,10)
arr2 = arr.copy()

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Multiplica cada dato del array por 2
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# Suma a cada elemento del array 2
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
# Divide 1 entre cada elemento del array

# NOTA: lanza una advertencia por la divisón entre 0, pero aún así terminará de resolver las operaciones faltantes

1 / arr

C:\Users\diego\AppData\Local\Temp\ipykernel_19984\2118896943.py:5: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [21]:
# Eleva al cuadrado cada número del array
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
# Suma dos arrays termino por termino
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Matrices

In [23]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
# Suma dos matrices termino por termino
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [25]:
# Producto punto

# Forma 1:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [26]:
# Forma 2:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])