In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,20)
arr

array([ 9, 17,  3, 18,  4,  7,  8,  2,  7,  8,  4,  1,  1, 15, 15, 10,  4,
       12,  8,  8], dtype=int32)

In [3]:
matriz = arr.reshape(4,5)
matriz

array([[ 9, 17,  3, 18,  4],
       [ 7,  8,  2,  7,  8],
       [ 4,  1,  1, 15, 15],
       [10,  4, 12,  8,  8]], dtype=int32)

In [4]:
tensor = arr.reshape(2,2,5)
tensor

array([[[ 9, 17,  3, 18,  4],
        [ 7,  8,  2,  7,  8]],

       [[ 4,  1,  1, 15, 15],
        [10,  4, 12,  8,  8]]], dtype=int32)

# Máximos y mínimos

In [5]:
# Arroja el número más grande dentro de un array:
arr.max()

np.int32(18)

In [6]:
# Sin parametro, arroja el número más grande dentro de toda la matriz:
print(f'Número más alto en toda la matriz: {matriz.max()}')

# Parámetros:
# 0 --> El número más grande por columna
# 1 --> El número más grande por fila
# n --> En número más grande en la n-1 dimensión
print(f'Número más alto por cada columna: {matriz.max(0)}')
print(f'Número más alto por cada fila: {matriz.max(1)}')

Número más alto en toda la matriz: 18
Número más alto por cada columna: [10 17 12 18 15]
Número más alto por cada fila: [18  8 15 12]


In [7]:
print(f'Números más altos de la dimensión 1:\n{tensor.max(0)}\n')
print(f'Números más altos de la dimensión 2:\n{tensor.max(1)}\n')
print(f'Números más altos de la dimensión 3:\n{tensor.max(2)}')


Números más altos de la dimensión 1:
[[ 9 17  3 18 15]
 [10  8 12  8  8]]

Números más altos de la dimensión 2:
[[ 9 17  3 18  8]
 [10  4 12 15 15]]

Números más altos de la dimensión 3:
[[18  8]
 [15 12]]


In [8]:
# Arroja el índice dónde se encuentra el valor más grande del array:
# - Si se repite el número, arroja el menor de los índices

# EJEMPLO: por columnas
matriz.argmax(0)

array([3, 0, 3, 0, 2])

In [9]:
# Arroja el número más pequeño dentro de un array:
arr.min()

np.int32(1)

In [10]:
matriz.min(0)

array([4, 1, 1, 7, 4], dtype=int32)

In [11]:
# Arroja el índice dónde se encuentra el valor más pequeño del array:
# - Si se repite el número, arroja el menor de los índices
arr.argmin()

np.int64(11)

In [12]:
matriz.argmin(0)

array([2, 2, 2, 1, 0])

# Operaciones estadísticas

In [ ]:
# Muestra la diferencia entre el dato de mayor a menor valor
np.ptp(arr)

np.int32(17)

In [16]:
np.ptp(matriz, 0) # por columnas

array([ 6, 16, 11, 11, 11], dtype=int32)

In [17]:
# Ordena los datos del array de menor a mayor
arr.sort()
arr

array([ 1,  1,  2,  3,  4,  4,  4,  7,  7,  8,  8,  8,  8,  9, 10, 12, 15,
       15, 17, 18], dtype=int32)

In [18]:
# Cálcula el percentil requerido
np.percentile(arr,50)

np.float64(8.0)

In [19]:
# Cálcula la mediana

print(f'{np.median(arr)}\n')
print(np.median(matriz,1))

8.0

[ 2.  7.  8. 15.]


In [20]:
# Desviación estandar
np.std(arr) 

np.float64(5.0445515162400705)

In [21]:
# Varianza
np.var(arr)

np.float64(25.447499999999998)

In [22]:
# Media
np.mean(arr)

np.float64(8.05)

# Concatenear arrays

In [23]:
# concatenar
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

print(a.ndim)
print(b.ndim)

2
1


In [24]:
# Para concatenar arrays deben tener las mismas dimensiones en el eje que se desean concatenar

# En este caso, se agrega una dimensión en el axis 0 a b
b = np.expand_dims(b,axis=0)
b.ndim

2

In [25]:
# Ya que tienen las mismas dimensiones en el axis 0, se pueden concatenar
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
# Si se quisieran concatenar en el axis 1, debería modificarse b
# En este caso, se le puede agregar una dimensión en axis=1 como ya vimos
# O usar su transpuesta con .T
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# Operaciones de algebra lineal

In [27]:
# Matriz transpuesta
b.T

array([[5],
       [6]])